name: Deploy to Railway

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy service to Railway
        uses: railwayapp/railway-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
          service: find-client

